if(WIN32)
	SET (IRRLICHT_ENABLE_X11_SUPPORT OFF CACHE BOOL "Enabled X11 support.")
else()
	SET (IRRLICHT_ENABLE_X11_SUPPORT ON CACHE BOOL "Enabled X11 support.")
endif()

if (IRRLICHT_ENABLE_X11_SUPPORT)
	if (WIN32)
		message(FATAL SEND_ERROR "X11 support is not possible on Windows!")
	else ()
		message(STATUS "Enable X11 support...")
	endif ()
else ()
	if (UNIX)
		message(FATAL SEND_ERROR "X11 support is mandatory on Unix like operating systems!")
	endif ()
endif ()
